package br.com.starcode.dao;

import java.sql.Connection;
import java.util.Calendar;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.AfterClass;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import br.com.starcode.dao.TurmaDAO;
import br.com.starcode.domain.Turma;

public class TurmaDaoTest {
	
	private static TurmaDAO turmaDAO;
	
	@BeforeClass
	public static void setup() throws Exception {
		
		try {
			
			Class.forName("org.h2.Driver");

			JdbcDataSource ds = new JdbcDataSource();
			ds.setUrl("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1");
			ds.setUser("sa");
			ds.setPassword("sa");
			
			//Connection c = DriverManager.getConnection("jdbc:h2:mem:test", "sa", "sa");
			Connection c = ds.getConnection();
			
			c.prepareStatement(
				"create table TB_TURMA ( " +
		        "id integer generated by default as identity, " +
		        "descricao varchar(30), " +
		        "inicio_aulas date, " +
		        "primary key (id) )"
		    ).execute();
			
			turmaDAO = new TurmaDAO(ds);
			
		} catch (Throwable e) {
			e.printStackTrace();
		}
		
	}
	
	@AfterClass
	public static void destroy() throws Exception {
	}

	@Test
	public void testTurma() throws Exception {
		
		Turma novaTurma = new Turma();
		novaTurma.setDescricao("Primeiro Ano");
		Calendar c = Calendar.getInstance();
		c.set(2014, 9, 9, 0, 0, 0);
		c.set(Calendar.MILLISECOND, 0);
		novaTurma.setInicioAulas(c.getTime());

		//insere
		turmaDAO.insert(novaTurma);
		
		//verifica lista
		Assert.assertEquals(1, turmaDAO.list().size());
		
		//recupera
		Turma t = turmaDAO.find(novaTurma.getId());

		//verifica
		Assert.assertEquals("Primeiro Ano", t.getDescricao());
		Assert.assertEquals(new Integer(1), t.getId());
		Assert.assertEquals(c.getTime(), t.getInicioAulas());
		
		//altera
		t.setDescricao("Segundo Ano");
		turmaDAO.update(t);
		
		//recupera
		Turma t2 = turmaDAO.find(novaTurma.getId());
		
		//verifica
		Assert.assertEquals("Segundo Ano", t2.getDescricao());
		Assert.assertEquals(new Integer(1), t2.getId());
		Assert.assertEquals(c.getTime(), t2.getInicioAulas());
		
		//apaga
		turmaDAO.delete(1);
		
		//verifica lista (tem que estar vazia)
		Assert.assertEquals(0, turmaDAO.list().size());
		
		//sucesso!
		
	}
	
}
